"""
report_generator.py

Generates a Markdown reconnaissance report from agent memory.

This is intentionally student-level and easy to explain.
"""

from datetime import datetime
from pathlib import Path


def generate_markdown_report(memory_data: dict, output_path: str) -> str:
    """
    Generate a Markdown report from agent memory.

    Args:
        memory_data: dictionary from AgentMemory
        output_path: path where report should be saved

    Returns:
        path to the generated report
    """
    target = memory_data.get("target", "Unknown target")
    observations = memory_data.get("observations", {})
    agent_trace = memory_data.get("agent_trace", [])

    report = []
    report.append(f"# AI-Assisted OSINT Reconnaissance Report\n")
    report.append(f"**Target:** `{target}`  \n")
    report.append(f"**Generated at:** {datetime.utcnow().isoformat()}Z  \n")
    report.append(f"**Project:** CAI OSINT Recon Agent  \n")
    report.append("\n---\n")

    report.append("## 1. Project Scope\n")
    report.append(
        "This report was generated by a constrained AI-assisted reconnaissance workflow. "
        "The purpose is to collect public and non-destructive reconnaissance evidence "
        "from an authorized target and summarize the findings for defensive review.\n"
    )

    report.append("The workflow does **not** perform exploitation, brute force, credential testing, "
                  "denial-of-service testing, stealth, or persistence.\n")

    report.append("\n---\n")

    report.append("## 2. Target Validation\n")
    target_validation = observations.get("target_validation", {})
    report.append(f"- Original target: `{target_validation.get('original_target', 'N/A')}`\n")
    report.append(f"- Cleaned target: `{target_validation.get('cleaned_target', 'N/A')}`\n")
    report.append(f"- Resolved IP: `{target_validation.get('resolved_ip', 'N/A')}`\n")
    report.append(f"- Allowed: `{target_validation.get('allowed', 'N/A')}`\n")
    report.append(f"- Reason: {target_validation.get('reason', 'N/A')}\n")

    report.append("\n---\n")

    report.append("## 3. Reconnaissance Findings\n")

    add_dns_section(report, observations)
    add_whois_section(report, observations)
    add_nmap_section(report, observations)
    add_web_headers_section(report, observations)
    add_tls_section(report, observations)

    report.append("\n---\n")

    report.append("## 4. Agent Decision Trace\n")
    if agent_trace:
        report.append("| Step | Tool | Observation | Decision |\n")
        report.append("|---|---|---|---|\n")

        for step in agent_trace:
            report.append(
                f"| {step.get('step', '')} "
                f"| `{step.get('tool', '')}` "
                f"| {safe_table_text(step.get('observation', ''))} "
                f"| {safe_table_text(step.get('decision', ''))} |\n"
            )
    else:
        report.append("No agent trace was recorded.\n")

    report.append("\n---\n")

    report.append("## 5. Risk Interpretation\n")
    report.extend(generate_risk_interpretation(observations))

    report.append("\n---\n")

    report.append("## 6. Defensive Recommendations\n")
    report.extend(generate_recommendations(observations))

    report.append("\n---\n")

    report.append("## 7. Limitations\n")
    report.append(
        "- The scan was intentionally limited for safety and coursework demonstration.\n"
        "- The report is based only on collected evidence.\n"
        "- Findings are not proof of exploitable vulnerabilities.\n"
        "- Human validation is required before making security decisions.\n"
    )

    final_report = "\n".join(report)

    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as file:
        file.write(final_report)

    return str(output_file)


def add_dns_section(report: list, observations: dict):
    dns = observations.get("dns_lookup")

    report.append("\n### 3.1 DNS Lookup\n")

    if not dns:
        report.append("DNS lookup was not performed.\n")
        return

    report.append(f"- Success: `{dns.get('success')}`\n")
    report.append(f"- Hostname: `{dns.get('hostname', 'N/A')}`\n")
    report.append(f"- IP addresses: `{dns.get('ip_addresses', [])}`\n")

    if dns.get("error"):
        report.append(f"- Error: {dns.get('error')}\n")


def add_whois_section(report: list, observations: dict):
    whois = observations.get("whois_lookup")

    report.append("\n### 3.2 WHOIS Lookup\n")

    if not whois:
        report.append("WHOIS lookup was not performed.\n")
        return

    report.append(f"- Success: `{whois.get('success')}`\n")

    output = whois.get("output", "")
    if output:
        preview = "\n".join(output.splitlines()[:15])
        report.append("\nWHOIS output preview:\n\n")
        report.append("```text\n")
        report.append(preview)
        report.append("\n```\n")
    else:
        report.append("- No WHOIS output available.\n")

    if whois.get("error"):
        report.append(f"- Error: {whois.get('error')}\n")


def add_nmap_section(report: list, observations: dict):
    nmap = observations.get("nmap_scan")

    report.append("\n### 3.3 Nmap Scan\n")

    if not nmap:
        report.append("Nmap scan was not performed.\n")
        return

    report.append(f"- Success: `{nmap.get('success')}`\n")
    report.append(f"- Command: `{nmap.get('command', 'N/A')}`\n")

    open_ports = nmap.get("open_ports", [])

    if open_ports:
        report.append("\nOpen ports detected:\n\n")
        report.append("| Port | State | Service |\n")
        report.append("|---|---|---|\n")

        for port in open_ports:
            report.append(
                f"| `{port.get('port', '')}` "
                f"| `{port.get('state', '')}` "
                f"| `{port.get('service', '')}` |\n"
            )
    else:
        report.append("- No open ports detected in the limited scan.\n")

    if nmap.get("error"):
        report.append(f"- Error: {nmap.get('error')}\n")


def add_web_headers_section(report: list, observations: dict):
    headers = observations.get("web_headers")

    report.append("\n### 3.4 Web Headers\n")

    if not headers:
        report.append("Web header collection was not performed.\n")
        return

    report.append(f"- Success: `{headers.get('success')}`\n")

    for protocol in ["http", "https"]:
        data = headers.get(protocol)

        report.append(f"\n#### {protocol.upper()} Result\n")

        if not data:
            report.append("No data collected.\n")
            continue

        report.append(f"- URL: `{data.get('url', 'N/A')}`\n")
        report.append(f"- Success: `{data.get('success')}`\n")
        report.append(f"- Status code: `{data.get('status_code', 'N/A')}`\n")

        selected_headers = select_security_headers(data.get("headers", {}))

        if selected_headers:
            report.append("\nSelected headers:\n\n")
            report.append("| Header | Value |\n")
            report.append("|---|---|\n")

            for key, value in selected_headers.items():
                report.append(f"| `{key}` | `{safe_table_text(str(value))}` |\n")
        else:
            report.append("- No selected security headers found.\n")

        if data.get("error"):
            report.append(f"- Error: {data.get('error')}\n")


def add_tls_section(report: list, observations: dict):
    tls = observations.get("tls_check")

    report.append("\n### 3.5 TLS Certificate Check\n")

    if not tls:
        report.append("TLS check was not performed.\n")
        return

    report.append(f"- Success: `{tls.get('success')}`\n")

    cert = tls.get("certificate", {})

    if cert:
        report.append(f"- Not before: `{cert.get('not_before', 'N/A')}`\n")
        report.append(f"- Not after: `{cert.get('not_after', 'N/A')}`\n")
        report.append(f"- Is expired: `{cert.get('is_expired', 'N/A')}`\n")
        report.append(f"- Subject alternative names: `{cert.get('subject_alt_names', [])}`\n")

    if tls.get("error"):
        report.append(f"- Error: {tls.get('error')}\n")


def select_security_headers(headers: dict) -> dict:
    """
    Select common headers useful for security discussion.
    """
    important = [
        "server",
        "content-type",
        "strict-transport-security",
        "content-security-policy",
        "x-frame-options",
        "x-content-type-options",
        "referrer-policy",
        "permissions-policy",
    ]

    selected = {}

    lower_map = {key.lower(): key for key in headers.keys()}

    for name in important:
        original_key = lower_map.get(name)
        if original_key:
            selected[original_key] = headers[original_key]

    return selected


def generate_risk_interpretation(observations: dict) -> list:
    """
    Generate simple evidence-based risk interpretation.
    """
    lines = []

    nmap = observations.get("nmap_scan", {})
    open_ports = nmap.get("open_ports", [])

    if not open_ports:
        lines.append("- No open ports were detected in the limited scan, reducing visible attack surface.\n")
    else:
        lines.append(
            "- The target exposes one or more network services. "
            "From an offensive security perspective, exposed services increase the attack surface "
            "and may require version review, patch management, and monitoring.\n"
        )

    for port in open_ports:
        service = port.get("service", "")
        port_value = port.get("port", "")

        if service == "ssh" or port_value == "22/tcp":
            lines.append(
                "- SSH exposure was detected. This is not automatically a vulnerability, "
                "but weak passwords, poor access control, or outdated SSH versions could increase risk.\n"
            )

        if service in ["http", "https"] or port_value in ["80/tcp", "443/tcp"]:
            lines.append(
                "- Web service exposure was detected. Web services should be reviewed for secure headers, "
                "software version disclosure, TLS configuration, and unnecessary public access.\n"
            )

    headers = observations.get("web_headers", {})
    if headers:
        for protocol in ["http", "https"]:
            data = headers.get(protocol, {})
            response_headers = data.get("headers", {})

            if data.get("success") and "Server" in response_headers:
                lines.append(
                    "- The web server appears to expose a Server header. "
                    "This may reveal technology information useful during reconnaissance.\n"
                )

    tls = observations.get("tls_check", {})
    cert = tls.get("certificate", {})
    if cert.get("is_expired") is True:
        lines.append("- The TLS certificate appears expired, which can affect trust and secure communication.\n")

    if not lines:
        lines.append("- No major risk interpretation could be made from the collected evidence.\n")

    return lines


def generate_recommendations(observations: dict) -> list:
    """
    Generate simple defensive recommendations based on observations.
    """
    lines = []

    nmap = observations.get("nmap_scan", {})
    open_ports = nmap.get("open_ports", [])

    if open_ports:
        lines.append("- Disable unnecessary public services and keep required services patched.\n")
        lines.append("- Monitor authentication logs and network access attempts.\n")
        lines.append("- Use firewall rules to restrict access where possible.\n")
    else:
        lines.append("- Continue maintaining a minimal external attack surface.\n")

    for port in open_ports:
        service = port.get("service", "")
        port_value = port.get("port", "")

        if service == "ssh" or port_value == "22/tcp":
            lines.append("- For SSH, use key-based authentication, disable root login, and rate-limit login attempts.\n")

        if service in ["http", "https"] or port_value in ["80/tcp", "443/tcp"]:
            lines.append("- For web services, configure security headers and avoid unnecessary version disclosure.\n")

    tls = observations.get("tls_check", {})
    cert = tls.get("certificate", {})
    if cert:
        lines.append("- Review TLS certificate validity and renew certificates before expiry.\n")

    return lines


def safe_table_text(text: str) -> str:
    """
    Make text safe for Markdown tables.
    """
    return str(text).replace("|", "\\|").replace("\n", " ")